controller_list:
        # - name: vel_based_pos_traj_controller
        #   action_ns: follow_joint_trajectory
 - name: follow_joint_trajectory
   action_ns: ""
   type: FollowJointTrajectory
   joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint

 - name: gripper_action
   action_ns: ""
   type: GripperCommand
   default: true
   command_joint: s_model_finger_middle_joint_1
   joints:
      - s_model_palm_finger_1_joint
      - s_model_finger_1_joint_1
      - s_model_finger_1_joint_2
      - s_model_finger_1_joint_3
      - s_model_palm_finger_2_joint
      - s_model_finger_2_joint_1
      - s_model_finger_2_joint_2
      - s_model_finger_2_joint_3
      - s_model_finger_middle_joint_1
      - s_model_finger_middle_joint_2
      - s_model_finger_middle_joint_3
