controller_list:
  - name: fake_gripper_controller
    joints:
      - s_model_palm_finger_1_joint
      - s_model_finger_1_joint_1
      - s_model_finger_1_joint_2
      - s_model_finger_1_joint_3
      - s_model_palm_finger_2_joint
      - s_model_finger_2_joint_1
      - s_model_finger_2_joint_2
      - s_model_finger_2_joint_3
      - s_model_finger_middle_joint_1
      - s_model_finger_middle_joint_2
      - s_model_finger_middle_joint_3
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint