#In this version of the joint limits, the maximum velocity and acceleration is slow down for the use in the laboratory 

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
  finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.9
    has_acceleration_limits: false
    max_acceleration: 0.5
